[config]
# will be set to mainnet by default if omitted
rpc = "https://fullnode.mainnet.sui.io:443/"

[packages]
YieldFlow = { local = "../degenhive/yield_flow" }
DSuiVault = { local = "../degenhive/dSuiVault" }
PoolMath = { local = "../degenhive/math" }
DragonTrainer = { local = "../degenhive/dragon_trainer" }
QueenMaker = { local = "../degenhive/queen_maker" }
TwoCoinAmm = { local = "../degenhive/two_pool" }
ThreeCoinAmm = { local = "../degenhive/three_pool" }
DragonFood = { local = "../degenhive/dragon_food" }
